apiVersion: v1
kind: Service

metadata:
  name: bms-service

spec:
  selector:
    app: bms

  type: NodePort

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
